### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by MuadDev** [mpsych/mitochondria#1]
This repository seems very interessting and I would love to test it out!

However, I have some trouble to get it running because I do not know which packages and their versions are required. Could you provide those? Perhaps in a requirements.txt file? 

For instance, the UNET model seems to use the 'merge` class, which is no longer available in keras 2. It seems to be available in keras 1.2, but then the next error appears that the 'sequence' class is not available.. In short, it would be useful to know which packages and versions you used so that I can just use those.

Thanks!

**Comment by neopeg64** [comment]
I have the same problem here as well. Once I one-by-one install missing modules I just run into new errors and cannot get it running.

A "requirements" / "environment".txt would be very welcome to get it running, as the paper looks very nice!

**Comment by luozhengrong** [comment]
The UNET model seems to use the 'merge` class, which is no longer available in keras 2.

> This repository seems very interessting and I would love to test it out!
> 
> However, I have some trouble to get it running because I do not know which packages and their versions are required. Could you provide those? Perhaps in a requirements.txt file?
> 
> For instance, the UNET model seems to use the 'merge` class, which is no longer available in keras 2. It seems to be available in keras 1.2, but then the next error appears that the 'sequence' class is not available.. In short, it would be useful to know which packages and versions you used so that I can just use those.
> 
> Thanks!

I have the same problem. How can I solve it

**Comment by haehn** [comment]
Just saw this - it now works with the bundled environment.yml and we are retraining but already uploaded weights with accuracy > .93!
